name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  test:
    name: Build - Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test
  sonarcloud:
    name: Analyze with the SonarCloud
    needs: test
    runs-on: ubuntu-latest
    #    steps:
    #      - uses: actions/checkout@v2
    #        with:
    #          fetch-depth: 0
    #      - name: SonarCloud Scan
    #        run: mvn -B clean verify -Pcoverage,sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}
    #        env:
    #          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: mvn sonar:sonar -Dsonar.login=${{ secrets.SONAR_TOKEN }}